apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-connection-configmap
  namespace: app
  labels:
    app: pdss-back
data:
  # db-connection-string: Server=tcp:mssql-paas.database.windows.net,1433;Initial Catalog=ProductsDB;Persist Security Info=False;User ID=root;Password=root;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;
  db-connection-string: jdbc:sqlserver://pdss-db.database.windows.net:1433;database=pdss;user=rochdi@pdss-db;password=123Rbl456;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
