name: Install ad-m/github-push-action
on:
  push:
    branches:
      - main
jobs:
  install-action:
    runs-on: ubuntu-latest
    steps:
      - name: Install action
        uses: actions/checkout@v2
        with:
          path: actions
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Install action dependencies
        run: npm ci
      - name: Install action
        run: npm pack
      - name: Clean up
        run: rm -rf actions
